# Generated by Django 3.1.13 on 2025-03-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_auto_20250331_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('temperature', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
